version: '3.8'

services:
  api:
    build: .
    restart: always
    command: sh -c "rm -f /app/tmp/pids/server.pid; bundle install && ./bin/rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - ./:/app/:delegated
    environment:
      RAILS_ENV: development
      DB_HOST: postgres
      DB_USERNAME: mypguser
      DB_PASSWORD: mypassword
      DB_DATABASE: myapi
    depends_on:
      - postgres

  postgres:
    image: postgres:11.8-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapi
      POSTGRES_USER: mypguser
      POSTGRES_PASSWORD: mypassword

volumes:
  ? postgres
